### PR TITLE
Debian packaging preparations

### PR DESCRIPTION
**Pull request by jeremiah**
I've done some minor debianization and renamed the branch according to Debian custom so that tools like git-buildpackage should "just work."

### CODE REVIEW

**Comment by jeremiah** [comment]
In Debian the erlang package comes with the escript binary, not sure what that is not the case with Ubuntu. 

See https://github.com/PDXostc/rvi_core/issues/62 for build issue.

**Comment by mfeuer** [comment]
Merge conflict. Could we rebase and try again?

**Comment by jeremiah** [comment]
On Wed, Dec 02, 2015 at 12:08:25PM -0800, Magnus Feuer wrote:
> Merge conflict. Could we rebase and try again?

Yes, will do.

**Comment by uwiger** [comment]
An alternative location for Erlang packages would be

https://www.erlang-solutions.com/resources/download.html

Erlang Solutions is an authorized support provider of Erlang, and also provides complete tested Erlang/OTP builds for a number of platforms, including Ubuntu.

**Comment by mfeuer** [comment]
I vote for using ESL's builds since they are a stable and dependent source that cover multiple targets.
That minimizes our RVI core porting to the specific modules we are using.

**Comment by jeremiah** [comment]
Closing due to too many conflicts. Will create separate pull request.

**Comment by mfeuer** [comment]
I am doing a new run on the debian packaging in a separate branch that tracks master. I'll ping you when I'm done with the basics.

**Comment by jeremiah** [comment]
Awesome! Can I ask that you call the packaging branch "debian" per the git-buildpackage tool: http://honk.sigxcpu.org/projects/git-buildpackage/manual-html/gbp.import.html#GBP.BRANCH.NAMING
which then makes it easier for it to go into Debian directly: http://anonscm.debian.org/cgit/

But this is by no means a requirement.

**Comment by mfeuer** [comment]
Of course.
God Jul på dig, BTW.

**Comment by jeremiah** [comment]
God jul to you! Eller till dig menar jag. Swenglish!

**Pull request closed without merging**
