### PR TITLE
Enhanced rebar config script for cross compilation support.

### PR DESCRIPTION
**Pull request by rstreif**
Signed-off-by: Rudolf J Streif <rudolf.streif@gmail.com>

### CODE REVIEW

**Comment by uwiger** [comment]
Maybe @saleyn has some opinion on this?

**Comment by saleyn** [comment]
In this patch the location of the port program executable is determined by `CXX ++ " -dumpmachine"`.  However in `exec.erl:543`, it's specified as `erlang:system_info(system_architecture)`, just like it is currently done in the `rebar`'s script.  I don't know if this discrepancy would ever lead to different values on some platform, and therefore this seems a bit suspicious.

**Comment by rstreif** [comment]
@saleyn 

I actually tested that with the architecture I was working on and with which I discovered the issue in the first place: ARM. The output of the gcc cross-compiler with -dumpmachine and erlang:system_info(system_architecture) were the same. I now tested it on additional architectures to see if the target triplets match on them too. Here is the result:

Compiler: gcc -dumpmachine
Erlang:   erlang:system_info(system_architecture).


Target System           Compiler                        Erlang
------------------------------------------------------------------------------------
i586                    i586-poky-linux                 i586-poky-linux-gnu
x86-64                  x86_64-poky-linux               x86_64-poky-linux-gnu
arm                     arm-poky-linux-gnueabi          arm-poky-linux-gnueabi
arm64                   aarch64-poky-linux              aarch64-poky-linux-gnu
powerpc                 powerpc-poky-linux              powerpc-poky-linux-gnu

The triples are <targetarch>-<vendor>-<os>. <vendor> in my case is poky as I am using the Yocto Project to build. According to [1] <os> can be either <system> or <kernel>-<system>. Virtually all GCC compilers built for the various Linux distros use <targetarch>-<vendor>-linux, such as x86_64-redhat-linux for my build system. I guess that comes back to the old discussion whether the system is Linux or GNU/Linux.

For cross-builds I can never use erlang:system_info(system_architecture) as this gives the triplet of the build host. To make this consistent, I could add the -gnu to all triplets that are not ARM in rebar.config.script. I am not sure why the architecture distinction is necessary in the first place. I have looked at other C/C++ modules integrated with Erlang and they do not do that. They only have <module>/priv.

I already made some changes to the rebar.config.script so that it does not set ERL_EI_LIBDIR and ERL_CFLAGS anymore. I can provide them via env variables to rebar.

[1] https://www.gnu.org/software/autoconf/manual/autoconf-2.65/html_node/Specifying-Target-Triplets.html

**Comment by saleyn** [comment]
The reason behind the architecture suffix after `priv` is that it is possible to have a single installation of the library that's shared by multiple architectures.  E.g. in some deployments that was a read-only NFS mount with all 3rd party libs that was used via ERL_LIBS path by all client machines running all sorts of architectures.

You are welcome to submit a patch to https://github.com/saleyn/erlexec, and if it is backward-compatible, I'll merge it.

**Pull request closed without merging**
